2019-04-12 00:22:16:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-12 00:22:16:[m]: IN CONFIG...
2019-04-12 00:22:16:[m]: CONFIG OK.
2019-04-12 00:22:48:[m]: EXIT.
2019-04-12 00:25:02:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-12 00:25:02:[m]: IN CONFIG...
2019-04-12 00:25:02:[m]: CONFIG OK.
2019-04-12 00:25:19:[m]: EXIT.
2019-04-12 00:25:21:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-12 00:25:21:[m]: IN CONFIG...
2019-04-12 00:25:21:[m]: CONFIG OK.
2019-04-12 00:30:33:[m]: EXIT.
2019-04-12 00:31:48:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-12 00:33:33:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-12 00:34:25:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-12 00:34:26:[m]: IN CONFIG...
2019-04-12 00:34:26:[m]: CONFIG OK.
2019-04-12 00:35:24:[m]: EXIT.
2019-04-12 00:35:35:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-12 00:35:35:[m]: IN CONFIG...
2019-04-12 00:35:35:[m]: CONFIG OK.
2019-04-12 00:35:35:[m]: CREATING SLAVE SERVER @ PORT10701...
2019-04-12 00:35:35:[m]: SLAVE SERVER OK.RUNNING.
2019-04-12 00:36:02:[m]: EXIT.
2019-04-12 00:36:06:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-12 00:36:06:[m]: IN CONFIG...
2019-04-12 00:36:06:[m]: CONFIG OK.
2019-04-12 00:36:06:[m]: CREATING SLAVE SERVER @ PORT10701...
2019-04-12 00:36:06:[m]: SLAVE SERVER OK.RUNNING.
2019-04-12 00:37:22:[m]: EXIT.
2019-04-12 00:37:25:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-12 00:37:25:[m]: IN CONFIG...
2019-04-12 00:37:25:[m]: CONFIG OK.
2019-04-12 00:37:25:[m]: CREATING SLAVE SERVER @ PORT10701...
2019-04-12 00:37:25:[m]: SLAVE SERVER OK.RUNNING.
2019-04-12 00:37:27:[m]: EXIT.
2019-04-12 00:37:32:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-12 00:37:32:[m]: IN CONFIG...
2019-04-12 00:37:32:[m]: CONFIG OK.
2019-04-12 00:38:12:[m]: CREATING SLAVE SERVER @ PORT10701...
2019-04-12 00:38:12:[m]: SLAVE SERVER OK.RUNNING.
2019-04-12 00:39:46:[m]: EXIT.
2019-04-12 00:39:52:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-12 00:39:52:[m]: IN CONFIG...
2019-04-12 00:39:52:[m]: CONFIG OK.
2019-04-12 00:39:56:[m]: CREATING SLAVE SERVER @ PORT10701...
2019-04-12 00:39:56:[m]: SLAVE SERVER OK.RUNNING.
2019-04-12 00:40:48:[m]: EXIT.
2019-04-12 00:40:51:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-12 00:40:51:[m]: IN CONFIG...
2019-04-12 00:40:51:[m]: CONFIG OK.
2019-04-12 00:40:52:[m]: CREATING SLAVE SERVER @ PORT10701...
2019-04-12 00:40:52:[m]: SLAVE SERVER OK.RUNNING.
2019-04-12 00:42:34:[m]: EXIT.
2019-04-12 00:42:45:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-12 00:42:45:[m]: IN CONFIG...
2019-04-12 00:42:45:[m]: CONFIG OK.
2019-04-12 00:42:46:[m]: CREATING SLAVE SERVER @ PORT10701...
2019-04-12 00:42:46:[m]: SLAVE SERVER OK.RUNNING.
2019-04-12 00:43:29:[m]: EXIT.
2019-04-12 00:43:32:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-12 00:43:32:[m]: IN CONFIG...
2019-04-12 00:43:32:[m]: CONFIG OK.
2019-04-12 00:43:46:[m]: EXIT.
2019-04-12 00:44:34:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-12 00:44:34:[m]: IN CONFIG...
2019-04-12 00:44:34:[m]: CONFIG OK.
2019-04-12 00:45:00:[m]: EXIT.
2019-04-12 00:45:02:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-12 00:45:02:[m]: IN CONFIG...
2019-04-12 00:45:02:[m]: CONFIG OK.
2019-04-12 00:45:46:[m]: EXIT.
2019-04-12 00:45:47:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-12 00:45:47:[m]: IN CONFIG...
2019-04-12 00:45:47:[m]: CONFIG OK.
2019-04-12 00:45:57:[m]: EXIT.
2019-04-12 00:46:02:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-12 00:46:02:[m]: IN CONFIG...
2019-04-12 00:46:02:[m]: CONFIG OK.
2019-04-12 00:46:14:[m]: EXIT.
2019-04-12 00:46:16:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-12 00:46:16:[m]: IN CONFIG...
2019-04-12 00:46:16:[m]: CONFIG OK.
2019-04-12 00:46:39:[m]: EXIT.
2019-04-12 00:46:41:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-12 00:46:41:[m]: IN CONFIG...
2019-04-12 00:46:41:[m]: CONFIG OK.
2019-04-12 00:46:41:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-12 00:46:41:[m]: IN CONFIG...
2019-04-12 00:46:41:[m]: CONFIG OK.
2019-04-12 00:46:44:[m]: EXIT.
2019-04-12 00:46:45:[m]: EXIT.
2019-04-12 00:46:47:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-12 00:46:47:[m]: IN CONFIG...
2019-04-12 00:46:47:[m]: CONFIG OK.
2019-04-12 00:47:08:[m]: CREATING SLAVE SERVER @ PORT10701...
2019-04-12 00:47:08:[m]: SLAVE SERVER OK.RUNNING.
2019-04-12 00:48:02:[m]: EXIT.
2019-04-12 00:48:05:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-12 00:48:05:[m]: IN CONFIG...
2019-04-12 00:48:05:[m]: CONFIG OK.
2019-04-12 00:48:06:[m]: CREATING SLAVE SERVER @ PORT10701...
2019-04-12 00:48:06:[m]: SLAVE SERVER OK.RUNNING.
2019-04-12 00:55:18:[m]: EXIT.
2019-04-12 00:59:25:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-12 00:59:25:[m]: IN CONFIG...
2019-04-12 00:59:25:[m]: CONFIG OK.
2019-04-12 00:59:26:[m]: CREATING SLAVE SERVER @ PORT10701...
2019-04-12 00:59:26:[m]: SLAVE SERVER OK.RUNNING.
2019-04-12 01:01:15:[m]: EXIT.
2019-04-12 22:11:38:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-12 22:11:38:[m]: IN CONFIG...
2019-04-12 22:11:38:[m]: CONFIG OK.
2019-04-12 22:11:39:[m]: CREATING SLAVE SERVER @ PORT10701...
2019-04-12 22:11:39:[m]: SLAVE SERVER OK.RUNNING.
2019-04-12 22:32:44:[m]: EXIT.
2019-04-12 22:54:01:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-12 22:54:01:[m]: IN CONFIG...
2019-04-12 22:54:01:[m]: CONFIG OK.
2019-04-12 22:54:02:[m]: CREATING SLAVE SERVER @ PORT10701...
2019-04-12 22:54:02:[m]: SLAVE SERVER OK.RUNNING.
2019-04-13 00:01:55:[e]:  >> Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 369, in _communicate
    iotp_request = IOTPTransactionData(server_data, IOTP_SLAVE_CONF[KEY_SLAVE_ID])
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPTransactionData.py", line 29, in __init__
    self.__parse_data()
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPTransactionData.py", line 59, in __parse_data
    raise Exception(IOTPSlaveMessage.ResponseType.StatusCode.INVALID_REQUEST, "Slave ID is "
Exception: (400, 'Slave ID is wrong')

2019-04-13 00:03:03:[e]:  >> Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 369, in _communicate
    iotp_request = IOTPTransactionData(server_data, IOTP_SLAVE_CONF[KEY_SLAVE_ID])
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPTransactionData.py", line 29, in __init__
    self.__parse_data()
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPTransactionData.py", line 59, in __parse_data
    raise Exception(IOTPSlaveMessage.ResponseType.StatusCode.INVALID_REQUEST, "Slave ID is "
Exception: (400, 'Slave ID is wrong')

2019-04-13 00:04:58:[e]:  >> Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 369, in _communicate
    iotp_request = IOTPTransactionData(server_data, IOTP_SLAVE_CONF[KEY_SLAVE_ID])
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPTransactionData.py", line 29, in __init__
    self.__parse_data()
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPTransactionData.py", line 59, in __parse_data
    raise Exception(IOTPSlaveMessage.ResponseType.StatusCode.INVALID_REQUEST, "Slave ID is "
Exception: (400, 'Slave ID is wrong')

2019-04-13 00:06:09:[e]:  >> Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 369, in _communicate
    iotp_request = IOTPTransactionData(server_data, IOTP_SLAVE_CONF[KEY_SLAVE_ID])
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPTransactionData.py", line 29, in __init__
    self.__parse_data()
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPTransactionData.py", line 59, in __parse_data
    raise Exception(IOTPSlaveMessage.ResponseType.StatusCode.INVALID_REQUEST, "Slave ID is "
Exception: (400, 'Slave ID is wrong')

2019-04-13 00:08:28:[e]:  >> Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 369, in _communicate
    iotp_request = IOTPTransactionData(server_data, IOTP_SLAVE_CONF[KEY_SLAVE_ID])
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPTransactionData.py", line 29, in __init__
    self.__parse_data()
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPTransactionData.py", line 59, in __parse_data
    raise Exception(IOTPSlaveMessage.ResponseType.StatusCode.INVALID_REQUEST, "Slave ID is "
Exception: (400, 'Slave ID is wrong')

2019-04-13 00:21:48:[m]: EXIT.
2019-04-14 00:16:41:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-14 00:16:41:[m]: IN CONFIG...
2019-04-14 00:16:41:[m]: CONFIG OK.
2019-04-14 00:16:42:[m]: Creating Slave Listener @ PORT10701...
2019-04-14 00:16:42:[m]: Slave Listener is running OK.
2019-04-14 00:16:43:[m]: WAIT FOR CMD...
2019-04-14 00:19:21:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-14 00:19:21:[m]: IN CONFIG...
2019-04-14 00:19:21:[m]: CONFIG OK.
2019-04-14 00:19:22:[m]: Creating Slave Listener @ PORT10701...
2019-04-14 00:19:22:[m]: Slave Listener is running OK.
2019-04-14 00:19:23:[m]: WAIT FOR CMD...
2019-04-14 00:20:29:[m]: EXIT.
2019-04-14 00:20:34:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-14 00:20:34:[m]: IN CONFIG...
2019-04-14 00:20:34:[m]: CONFIG OK.
2019-04-14 00:20:35:[m]: Creating Slave Listener @ PORT10701...
2019-04-14 00:20:35:[m]: Slave Listener is running OK.
2019-04-14 00:20:36:[m]: WAIT FOR CMD...
2019-04-14 00:22:11:[m]: EXIT.
2019-04-14 00:22:15:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-14 00:22:15:[m]: IN CONFIG...
2019-04-14 00:22:15:[m]: CONFIG OK.
2019-04-14 00:22:16:[m]: Creating Slave Listener @ PORT10701...
2019-04-14 00:22:16:[m]: Slave Listener is running OK.
2019-04-14 00:22:17:[m]: WAIT FOR CMD...
2019-04-14 00:23:46:[e]:  >> Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 254, in init_connection
    server_sock.connect((server_ip, port))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused

2019-04-14 00:24:23:[m]: EXIT.
2019-04-14 00:25:26:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-14 00:25:26:[m]: IN CONFIG...
2019-04-14 00:25:26:[m]: CONFIG OK.
2019-04-14 00:25:26:[e]:  >> Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 254, in init_connection
    server_sock.connect((server_ip, port))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused

2019-04-14 00:26:54:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-14 00:26:54:[m]: IN CONFIG...
2019-04-14 00:26:54:[m]: CONFIG OK.
2019-04-14 00:26:54:[e]:  >> Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 254, in init_connection
    server_sock.connect((server_ip, port))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused

2019-04-14 00:27:30:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-14 00:27:30:[m]: IN CONFIG...
2019-04-14 00:27:30:[m]: CONFIG OK.
2019-04-14 00:27:30:[e]:  >> Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 254, in init_connection
    server_sock.connect((server_ip, port))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused

2019-04-14 00:27:47:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-14 00:27:47:[m]: IN CONFIG...
2019-04-14 00:27:47:[m]: CONFIG OK.
2019-04-14 00:27:47:[e]:  >> Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 254, in init_connection
    server_sock.connect((server_ip, port))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused

2019-04-14 00:27:50:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-14 00:27:50:[m]: IN CONFIG...
2019-04-14 00:27:50:[m]: CONFIG OK.
2019-04-14 00:27:50:[e]:  >> Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 254, in init_connection
    server_sock.connect((server_ip, port))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused

Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 254, in init_connection
    server_sock.connect((server_ip, port))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused
2019-04-14 00:27:54:[e]:  >> Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 254, in init_connection
    server_sock.connect((server_ip, port))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused

Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 254, in init_connection
    server_sock.connect((server_ip, port))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused
2019-04-14 00:27:58:[e]:  >> Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 254, in init_connection
    server_sock.connect((server_ip, port))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused

Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 254, in init_connection
    server_sock.connect((server_ip, port))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused
2019-04-14 00:28:02:[m]: EXIT.
2019-04-14 00:28:08:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-14 00:28:08:[m]: IN CONFIG...
2019-04-14 00:28:08:[m]: CONFIG OK.
2019-04-14 00:28:08:[e]:  >> Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 254, in init_connection
    server_sock.connect((server_ip, port))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused

Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 254, in init_connection
    server_sock.connect((server_ip, port))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused
2019-04-14 00:28:11:[m]: EXIT.
