2019-04-14 00:28:41:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-14 00:28:41:[m]: IN CONFIG...
2019-04-14 00:28:41:[m]: CONFIG OK.
2019-04-14 00:28:41:[e]:  >> Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 254, in init_connection
    server_sock.connect((server_ip, port))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused

Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 254, in init_connection
    server_sock.connect((server_ip, port))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused
2019-04-14 00:28:46:[m]: Creating Slave Listener @ PORT10701...
2019-04-14 00:28:46:[m]: Slave Listener is running OK.
2019-04-14 00:28:47:[m]: WAIT FOR CMD...
2019-04-14 00:30:06:[e]:  >> Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 254, in init_connection
    server_sock.connect((server_ip, port))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused

Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 254, in init_connection
    server_sock.connect((server_ip, port))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused
2019-04-14 00:30:10:[e]:  >> Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 254, in init_connection
    server_sock.connect((server_ip, port))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused

Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 254, in init_connection
    server_sock.connect((server_ip, port))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused
2019-04-14 00:30:16:[m]: EXIT.
2019-04-14 00:30:19:[m]: Welcome to IOTP Slave version 2.1.7
2019-04-14 00:30:19:[m]: IN CONFIG...
2019-04-14 00:30:19:[m]: CONFIG OK.
2019-04-14 00:30:20:[m]: Creating Slave Listener @ PORT10701...
2019-04-14 00:30:20:[m]: Slave Listener is running OK.
2019-04-14 00:30:21:[m]: WAIT FOR CMD...
2019-04-14 00:31:02:[m]: WAIT FOR CMD...
2019-04-14 00:31:02:[m]: RX: E00010015D
2019-04-14 00:31:02:[m]: TX: {"status_code": 200, "message": [{"state": 1, "type": 13, "id": 1}, {"state": 1, "type": 13, "id": 2}, {"state": 1, "type": 13, "id": 3}, {"state": 1, "type": 13, "id": 4}], "status_text": "Success or OK", "id": "21"}\n
2019-04-14 00:31:16:[m]: WAIT FOR CMD...
2019-04-14 00:31:16:[m]: RX: E00060015D
2019-04-14 00:31:16:[m]: TX: {"status_code": 200, "message": [{"state": 1, "type": 13, "id": 1}, {"state": 1, "type": 13, "id": 2}, {"state": 1, "type": 13, "id": 3}, {"state": 1, "type": 13, "id": 4}], "status_text": "Success or OK", "id": "21"}\n
2019-04-14 00:31:22:[m]: WAIT FOR CMD...
2019-04-14 00:31:22:[m]: RX: C000700151D30000
2019-04-14 00:31:22:[m]: TX: {"status_code": 200, "message": "", "status_text": "Success or OK", "id": "21"}\n
2019-04-14 00:31:27:[m]: WAIT FOR CMD...
2019-04-14 00:31:27:[m]: RX: C000800151D10000
2019-04-14 00:31:28:[m]: TX: {"status_code": 200, "message": "", "status_text": "Success or OK", "id": "21"}\n
2019-04-14 00:31:32:[m]: WAIT FOR CMD...
2019-04-14 00:31:32:[m]: RX: C000900151D20000
2019-04-14 00:31:32:[m]: TX: {"status_code": 200, "message": "", "status_text": "Success or OK", "id": "21"}\n
2019-04-14 00:31:36:[m]: WAIT FOR CMD...
2019-04-14 00:31:36:[m]: RX: C000A00151D40000
2019-04-14 00:31:36:[m]: TX: {"status_code": 200, "message": "", "status_text": "Success or OK", "id": "21"}\n
2019-04-14 00:31:41:[m]: WAIT FOR CMD...
2019-04-14 00:31:41:[m]: RX: E000B0015D
2019-04-14 00:31:41:[m]: TX: {"status_code": 200, "message": [{"state": 0, "type": 13, "id": 1}, {"state": 0, "type": 13, "id": 2}, {"state": 0, "type": 13, "id": 3}, {"state": 0, "type": 13, "id": 4}], "status_text": "Success or OK", "id": "21"}\n
2019-04-14 00:32:01:[m]: WAIT FOR CMD...
2019-04-14 00:32:01:[m]: RX: E00110015D
2019-04-14 00:32:01:[m]: TX: {"status_code": 200, "message": [{"state": 0, "type": 13, "id": 1}, {"state": 0, "type": 13, "id": 2}, {"state": 0, "type": 13, "id": 3}, {"state": 0, "type": 13, "id": 4}], "status_text": "Success or OK", "id": "21"}\n
2019-04-14 00:34:07:[m]: WAIT FOR CMD...
2019-04-14 00:34:07:[m]: RX: E00160015D
2019-04-14 00:34:07:[m]: TX: {"status_code": 200, "message": [{"state": 0, "type": 13, "id": 1}, {"state": 0, "type": 13, "id": 2}, {"state": 0, "type": 13, "id": 3}, {"state": 0, "type": 13, "id": 4}], "status_text": "Success or OK", "id": "21"}\n
2019-04-14 00:40:20:[e]:  >> Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 254, in init_connection
    server_sock.connect((server_ip, port))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused

Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 254, in init_connection
    server_sock.connect((server_ip, port))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused
2019-04-14 00:40:24:[e]:  >> Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 254, in init_connection
    server_sock.connect((server_ip, port))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused

Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 254, in init_connection
    server_sock.connect((server_ip, port))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused
2019-04-14 00:40:28:[e]:  >> Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 254, in init_connection
    server_sock.connect((server_ip, port))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused

Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 254, in init_connection
    server_sock.connect((server_ip, port))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused
2019-04-14 00:40:32:[e]:  >> Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 254, in init_connection
    server_sock.connect((server_ip, port))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused

Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 254, in init_connection
    server_sock.connect((server_ip, port))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused
2019-04-14 00:40:36:[e]:  >> Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 254, in init_connection
    server_sock.connect((server_ip, port))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused

Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 254, in init_connection
    server_sock.connect((server_ip, port))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused
2019-04-14 00:40:40:[e]:  >> Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 254, in init_connection
    server_sock.connect((server_ip, port))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused

Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 254, in init_connection
    server_sock.connect((server_ip, port))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused
2019-04-14 00:40:44:[e]:  >> Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 254, in init_connection
    server_sock.connect((server_ip, port))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused

Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 254, in init_connection
    server_sock.connect((server_ip, port))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused
2019-04-14 00:40:47:[m]: EXIT.
2019-04-14 00:40:48:[e]:  >> Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 254, in init_connection
    server_sock.connect((server_ip, port))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused

Traceback (most recent call last):
  File "/Users/soumensardar/Google Drive/IOTP Implementation/git/IOTPSlave/IOTPSlaveCore/IOTPSlave.py", line 254, in init_connection
    server_sock.connect((server_ip, port))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 61] Connection refused
